"""initial1

Revision ID: 008a35300e38
Revises: b0f383a522dd
Create Date: 2023-11-16 21:18:56.071233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008a35300e38'
down_revision: Union[str, None] = 'b0f383a522dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('day', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'day')
    # ### end Alembic commands ###
