"""initial

Revision ID: 0a55a4b06bd2
Revises: 
Create Date: 2023-12-25 18:38:00.440157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a55a4b06bd2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_name', sa.String(length=250), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('start', sa.String(length=250), nullable=False),
    sa.Column('end', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('next', sa.String(length=250), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=250), nullable=False),
    sa.Column('room', sa.String(length=250), nullable=True),
    sa.Column('classroom', sa.String(length=250), nullable=False),
    sa.Column('edit_lesson', sa.String(length=250), nullable=True),
    sa.Column('edit_room', sa.String(length=250), nullable=True),
    sa.Column('edit_next', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pupil',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('class_num', sa.Integer(), nullable=False),
    sa.Column('class_letter', sa.String(length=250), nullable=False),
    sa.Column('school_name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('class_num', sa.Integer(), nullable=True),
    sa.Column('class_letter', sa.String(length=250), nullable=True),
    sa.Column('head_teacher', sa.Boolean(), nullable=False),
    sa.Column('director', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    op.drop_table('pupil')
    op.drop_table('lesson')
    op.drop_table('journal')
    op.drop_table('classroom')
    # ### end Alembic commands ###
