"""edit

Revision ID: 20944be7f72a
Revises: d5dac05e414f
Create Date: 2023-11-25 18:05:11.652634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20944be7f72a'
down_revision: Union[str, None] = 'd5dac05e414f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('edit_lesson', sa.String(length=250), nullable=True))
    op.add_column('lesson', sa.Column('edit_room', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'edit_room')
    op.drop_column('lesson', 'edit_lesson')
    # ### end Alembic commands ###
