"""edit_next

Revision ID: 51d61fd5d101
Revises: fb65959267b9
Create Date: 2023-11-29 12:22:25.615437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d61fd5d101'
down_revision: Union[str, None] = 'fb65959267b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('edit_next', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'edit_next')
    # ### end Alembic commands ###
