"""initial1

Revision ID: d5dac05e414f
Revises: 11f774105759
Create Date: 2023-11-24 21:52:20.872142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd5dac05e414f'
down_revision: Union[str, None] = '11f774105759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'class_num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('teacher', 'class_letter',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'class_letter',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('teacher', 'class_num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
