"""initial1

Revision ID: fb65959267b9
Revises: b131bb9665b9
Create Date: 2023-11-26 16:11:39.773266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb65959267b9'
down_revision: Union[str, None] = 'b131bb9665b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pupil', sa.Column('school_name', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pupil', 'school_name')
    # ### end Alembic commands ###
